# Site settings
title: 차태민 블로그
url: "https://hubcodes.github.io"
baseurl: ""
description: >
    차태민 블로그

# My information
email: krlrhkstk12@gmail.com
author: 차태민 (Taemin Cha)
profile: 
github_username: HubCodes
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
utterances:
  repo: HubCodes/hubcodes.github.io
  issue-term: pathname
  label: Comment
  branch: master

blame: "https://github.com/HubCodes/hubcodes.github.io/blame/master/_wiki"
edit: "https://github.com/HubCodes/hubcodes.github.io/edit/master/_wiki"
issue: "https://github.com/HubCodes/hubcodes.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
